/** @deprecated Importar desde `@/lib/contract-config` */
export {
  contractConfigs,
  contractSchemas,
  createEmptyFormValues,
  getAllConfigSlugs,
  getAllSchemaSlugs,
  getConfigFields,
  getContractConfig,
  getContractSchema,
  getSchemaFields,
  hasConfigForSlug,
  hasSchemaForSlug,
  validateConfig,
  validateField,
  validateSchema,
  validateStep,
  type ContractConfig,
  type ContractFieldDefinition,
  type ContractFieldOption,
  type ContractFieldType,
  type ContractSchema,
  type ContractStepDefinition,
} from "@/lib/contract-config";
